### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by lizzeth99** [SistemasTecTlaxiaco/infografia-lizzeth99#1]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lizzeth99/files/8064853/INFOGRAFIA.pdf)

**Comment by garaudy12** [comment]
Excelente trabajo cumple con las características que se piden.
calificación:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
