### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by lizzeth99** [SistemasTecTlaxiaco/infografia-lizzeth99#2]
![Azul Personalidad de Emprendedores Negocio Infografía](https://user-images.githubusercontent.com/72048309/110197042-65f30780-7e0e-11eb-82a4-77dd66268274.jpg)

**Comment by JeserLeonel** [comment]
Excelente trabajo. Incluyó todas las partes indicadas de una infografía. Todas las gráficas están relacionadas al tema y lo hacen fácil de entender. Las fuentes de las gráficas prestadas están citadas. El tema es claro y bien enfocado. Destaca la idea principal y es respaldada con información detallada. Los diagramas e ilustraciones son ordenados y precisos, se combinan perfectamente con el texto para mejorar el entendimiento del tema. Los gráficos usados en la infografía reflejan creatividad.

**Comment by JeserLeonel** [comment]
20 puntos 100%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
